### ISSUE TITLE
Offset sticky element from top?

### ISSUE THREAD

**Issue by SachaG** [jackmoore/react-sticky-position#3]
When I use this component, the sticky element always sticks flush with the top of the screen. Is there a way to have it stick, say, 10 pixels down from the top? I can't just adding padding to the top of the element because if I did that it'd be offset all the time, even when it isn't pinned yet.

**Comment by jackmoore** [comment]
Give the element a top position in your CSS or on the style attribute, just like you would for native sticky-position.  For example:

```
.sticky {
  top: 10px;
  position: sticky;
}
```

**Comment by SachaG** [comment]
Thanks! For reference's sake, this is what I had:

```
render() {
  return (
    <Sticky>
      <div className="sidebar">
          ...
      </div>
    </Sticky>
  )
}
```

And then in my CSS, I did:

```
.sticky{
  top: 10px;
}
```
